
if(top.location!=self.location){top.location=self.location.href;}
var GlobSearch={show:null,init:function(){var q=$('q');if(!q){return;}
Event.observe(q,'focus',GlobSearch.on,false);Event.observe(q,'blur',GlobSearch.off,false);var t=$('q-tabs').getElementsByTagName('label');for(var i=0;i<t.length;i++){Event.observe(t[i],'click',function(){GlobSearch.untab();this.addClassName('on');},false);}},on:function(){this.select();if(GlobSearch.show){clearTimeout(GlobSearch.show);}
if(this.value=='Search …'){this.value='';}
$('q-tabs').addClassName('on');},off:function(){if(!this.value){this.value='Search …';}
GlobSearch.show=setTimeout('GlobSearch.out()',15000);},out:function(){$('q-tabs').removeClassName('on');clearTimeout(GlobSearch.show);},untab:function(){var t=$('q-tabs').getElementsByTagName('label');for(var i=0;i<t.length;i++){t[i].removeClassName('on');}
return;}};var MSG={init:function(){var msgbox=$('msg');if(!msgbox){return;}
Event.observe(msgbox,"mouseup",MSG.hide,false);$$('input.error').each(function(s){Event.observe(s,'focus',function(){this.removeClassName('error');});});},show:function(msg,id,stat){var container=$(id)||$('m');var msgbox=$('msg');if(!msgbox){msgbox=document.createElement("div");msgbox.id="msg";Event.observe(msgbox,"mouseup",MSG.hide,false);}
if(!msgbox.parentNode||msgbox.parentNode!=container){(container.firstChild)?container.insertBefore(msgbox,container.firstChild):container.appendChild(msgbox);}
msgbox.className=stat;msgbox.innerHTML=msg||"";var scrollTop=(document.documentElement)?document.documentElement.scrollTop:document.body.scrollTop;var msgTop=Position.cumulativeOffset($('msg'))[1];if(msgTop<scrollTop){msgbox.scrollIntoView(true);}
Effect.Fade(msgbox,{from:0,to:1.0,duration:1.0,queue:'end'});},hide:function(){var msgbox=$('msg')||null;if(!msgbox){return;}
Effect.Fade(msgbox);var container=$('m');if(msgbox!=container.firstChild){container.insertBefore(msgbox,container.firstChild);}},success:function(msg,id){MSG.show(msg,id,'success');},failed:function(msg,id){MSG.show(msg,id,'failed');},neutral:function(msg,id){MSG.show(msg,id,'neutral');},refresh:function(msg,id){MSG.show(msg,id,'refresh');},error:function(msg,id){MSG.show(msg,id,'error');}};var Fav={t:null,h:null,init:function(t,h){Fav.t=encodeURIComponent(t);Fav.h=encodeURIComponent(h);$$('#m a.fav').each(function(a){Event.observe(a,'mousedown',Fav.add,false);Event.observe(a,'click',function(event){Event.stop(event);return false;},false);});$$('#frame-nav a.fav').each(function(a){Event.observe(a,'mousedown',Fav.add,false);Event.observe(a,'click',function(event){Event.stop(event);return false;},false);});},add:function(event){Event.stop(event);Event.stopObserving(this,'mousedown',Fav.add);Event.stopObserving(this,'click');Fav.post(this,'add');this.innerHTML='<span>&#10003;</span> Favorite';},post:function(a,action){var act=(action=='rm')?'set=rm':'set=add';var tok='&t='+Fav.t+'&h='+Fav.h;new Ajax.Request(url=a.href,{method:'post',requestHeaders:{'X-pss-xhr':1},parameters:act+tok,onSuccess:function(){if(_gaq){_gaq.push(['_trackPageview',url]);}},onFailure:function(){}});}};var OverBox={src:null,init:function(){$$('a.o-b').each(function(a){Event.observe(a,'click',OverBox.on,false);});Event.observe($('o-close'),'mousedown',OverBox.off,false);},on:function(event){Event.stop(event);if(!Event.isLeftClick(event)){return true;}
OverBox.setFrame(this.href);Element.addClassName($('o-box'),'on');return false;},off:function(){Element.removeClassName($('o-box'),'on');return false;},setFrame:function(url){var iframe=$('o-iframe');if(iframe){iframe.src=url;return false;}
iframe=document.createElement('iframe');iframe.id='o-iframe';iframe.src=url;$('o-main').appendChild(iframe);Event.observe(iframe,'load',OverBox.fixSize,false);return false;},fixSize:function(){var frame=$('o-iframe');if(frame.src==OverBox.src){return false;}
var innerDoc=(frame.contentDocument)?frame.contentDocument:frame.contentWindow.document;frame.style.height=innerDoc.body.scrollHeight+20+'px';frame.style.width=innerDoc.body.scrollWidth+20+'px';OverBox.src=frame.src;return false;}};var DL={frame:null,init:function(){DL.frame=$('frame-dl');if(!DL.frame){return false;}
Event.observe(window,'resize',DL.resize);DL.resize();Event.observe('bt-dl','click',DL.fx);},resize:function(){DL.frame.style.height=document.body.offsetHeight-36+"px";return false;},fx:function(event){Event.stop(event);DL.frame.style.top="0";DL.frame.style.height="100%";Effect.DropOut('frame-top');setTimeout("window.location=DL.frame.src",1000);}};var CAL={init:function(){var cal=$('cal');if(!cal){return;}
$$('#cal button').each(function(b){Event.observe(b,'mousedown',CAL.get,false);});},get:function(event){var targ=Event.element(event)||null;if(targ.nodeName!='BUTTON'){targ=targ.parentNode;}
$$('#cal button').each(function(b){Event.stopObserving(b,'mousedown',CAL.get,false);});new Ajax.Request(url=$('cal').getAttribute('action'),{method:'get',requestHeaders:{'X-pss-xhr':1},parameters:targ.name+'='+targ.value,onSuccess:function(transport){$('cal').innerHTML=transport.responseText;$$('#cal button').each(function(b){Event.observe(b,'mousedown',CAL.get,false);});if(_gaq){_gaq.push(['_trackPageview',url]);}},onFailure:function(){}});}};var TAB={init:function(){$$('#files-home .tab a').each(function(a){if(a.innerHTML!='Other'){Event.observe(a,'mousedown',TAB.post,false);Event.observe(a,'click',function(event){Event.stop(event);return false;},false);}});},rmOn:function(){$$('#files-home .tab').each(function(b){b.className='tab';});},post:function(event){var targ=Event.element(event)||null;Event.stop(event);var oldOn;targ.parentNode.className='tab on';$('files-home-list').style.opacity=0.5;oldOn=$$('#files-home .on');TAB.rmOn();targ.parentNode.className='tab on';new Ajax.Request(url=targ.href,{method:'post',requestHeaders:{'X-pss-xhr':1},onSuccess:function(transport){$("files-home-list").innerHTML=transport.responseText;$("files-home-next").href=targ.href+"page2/";$('files-home-list').style.opacity=1;if(_gaq){_gaq.push(['_trackPageview',url]);}},onFailure:function(){targ.parentNode.className='tab';oldOn.className='tab on';$('files-home-list').style.opacity=1;}});}};var JUMP={init:function(){if(!$('page-jump')){return false;}
$('page-jump').style.display='block';Event.observe('jump','keyup',JUMP.fix,false);Event.observe('jump','focus',function(){var j=$('jump').value.replace(/[^0-9]/g,'');j=parseInt(j);var p=($('page-max').value==$('page').value)?1:$('page-max').value;$('jump').value=(isNaN(j))?p:j;$('jump').select();},false);Event.observe('jump','blur',function(){$('jump').value='';},false);Event.observe('page-jump','submit',function(e){Event.stop(e);$('jump').setAttribute('readonly','true');JUMP.fix();var j=$('jump').value.replace(/[^0-9]/g,'');j=parseInt(j);if(isNaN(j)||j<1){return false;}
var p=$('page').value.replace(/[^0-9]/g,'')||1;var cur=$('nv').getElementsByClassName('on')[0];var w=cur.href;if(w.indexOf('/page'+p)>0){w=w.replace('/page'+p+'/','/page'+j+'/');}
else{w=w.replace(/\/+$/,'');w=w+'/page'+j+'/';}
window.location=w;return false;},false);},fix:function(){var j=$('jump').value.replace(/[^0-9]/g,'');if(j==''){return false;}
var m=$('page-max').value;j=parseInt(j);m=parseInt(m);if(isNaN(j)||(j>m)){j=m;$('jump').value=j;$('jump').select();}
else{$('jump').value=j;}
return false;}};var LV={init:function(){var lv=$('lv');if(!lv){return;}
Event.observe('lv','mouseup',LV.toggle);$('lv').style.display='block';return false;},toggle:function(){if($('m').hasClassName('sm')){COOKIE.rm('L');$('m').removeClassName('sm');}
else{COOKIE.set('L',1,'/',365);$('m').addClassName('sm');}}};var COOKIE={get:function(name){name=name+"=";var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var c=cookies[i];while(c.charAt(0)==' '){c=c.substring(1,c.length);}
if(c.indexOf(name)===0){return c.substring(name.length,c.length);}}
return null;},set:function(name,value,path,days){var expires;if(days){var dt=new Date();dt.setTime(dt.getTime()+(days*86400000));expires="; expires="+dt.toGMTString();}
else{expires="";}
var path="; path="+path;document.cookie=name+"="+value+expires+path;return false;},rm:function(name){COOKIE.set(name,"",'/',-1);return false;}};var VOTE={init:function(){$$('.vote-view a').each(function(s){Event.observe(s,'click',function(event){var targ=Event.element(event)||null;Event.stop(event);this.parentNode.parentNode.parentNode.addClassName('voted');return false;});});return false;}};var Contact={init:function(){var cf=$('contact-form');if(!cf){return;}
Event.observe('contact-form','submit',Contact.doSubmit,false);$$('#contact-form input').each(function(inp){Event.observe(inp,'keyup',Contact.fix,false);});$$('#contact-form textarea').each(function(inp){Event.observe(inp,'keyup',Contact.fix,false);});Event.observe('reason','change',Contact.reason,false);if(window.location.hash&&window.location.hash=='#advisories'){$('reason').value='advisories';}
Contact.reason();return true;},isGood:function(inp){if(inp.getAttribute('pattern')&&!inp.value.match(inp.getAttribute('pattern'))){inp.addClassName('error');return false;}
inp.removeClassName('error');return true;},fix:function(e){var targ=Event.element(e)||null;if(targ){targ.removeClassName('error');}
return true;},doSubmit:function(e){$$('#contact-form input[required]').each(function(inp){Contact.isGood(inp)});$$('#contact-form textarea[required]').each(function(inp){Contact.isGood(inp)});if($$('#contact-form .error').length>0){$$('#contact-form .error')[0].focus();e.stop();return false;}
document.body.setStyle({cursor:"wait"});$('contact-form').stopObserving('click',Contact.doSubmit);$('contact-form').submit();return true;},reason:function(){$('contact-form').removeClassName('services');$$('#reason option').each(function(opt){$('contact-'+opt.value).style.display=(opt.selected)?'block':'none';document.getElementsByClassName('contact-'+opt.value)[0].style.display=(opt.selected)?'block':'none';if(opt.selected&&opt.value=='services'){$('contact-form').addClassName('services');}});return true;}};document.observe('dom:loaded',function(){GlobSearch.init();OverBox.init();DL.init();CAL.init();MSG.init();TAB.init();JUMP.init();LV.init();Contact.init();setTimeout('window.location.reload(true)',1800000);});